# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [192]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [193]:
# your code here
print(np.__version__)

1.20.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [194]:
# Method 1
rg = np.random.default_rng(1) 
a=rg.random((2,3,5)) 
a

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

In [195]:
# Method 2
a= np.random.rand(2,3,5)
a

array([[[0.18735616, 0.91996607, 0.66168682, 0.35465348, 0.95358968],
        [0.1451573 , 0.17339121, 0.5091223 , 0.02587329, 0.46096725],
        [0.87327477, 0.05154621, 0.87417141, 0.30936865, 0.58303425]],

       [[0.59384567, 0.08075741, 0.73852591, 0.70636762, 0.03926711],
        [0.81522137, 0.61002174, 0.51947912, 0.54601431, 0.21277006],
        [0.44711181, 0.35430245, 0.75567209, 0.12113423, 0.58731077]]])

In [175]:
# Method 3
a = np.random.randint(100, size=(2,3,5)) #range 100, size 2,3,5

#### 4. Print *a*.


In [196]:
# your code here
a

array([[[0.18735616, 0.91996607, 0.66168682, 0.35465348, 0.95358968],
        [0.1451573 , 0.17339121, 0.5091223 , 0.02587329, 0.46096725],
        [0.87327477, 0.05154621, 0.87417141, 0.30936865, 0.58303425]],

       [[0.59384567, 0.08075741, 0.73852591, 0.70636762, 0.03926711],
        [0.81522137, 0.61002174, 0.51947912, 0.54601431, 0.21277006],
        [0.44711181, 0.35430245, 0.75567209, 0.12113423, 0.58731077]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [197]:
# your code here
b = np.full((5,2,3),1)

#### 6. Print *b*.


In [198]:
# your code here
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [199]:
# your code here
if a.size == b.size:
    print('a and b have the same size')
else:
    print('they do not have the same size')

a and b have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [200]:
# your answer here
a+b
# Cannot be added together because shapes are not the same 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [201]:
# your code here
c = np.reshape(b,(2,3,5))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [202]:
# your code/answer here
d = a+c
d
# It works because each value in array a has it mirror value in array d , so they can be summed up.

array([[[1.18735616, 1.91996607, 1.66168682, 1.35465348, 1.95358968],
        [1.1451573 , 1.17339121, 1.5091223 , 1.02587329, 1.46096725],
        [1.87327477, 1.05154621, 1.87417141, 1.30936865, 1.58303425]],

       [[1.59384567, 1.08075741, 1.73852591, 1.70636762, 1.03926711],
        [1.81522137, 1.61002174, 1.51947912, 1.54601431, 1.21277006],
        [1.44711181, 1.35430245, 1.75567209, 1.12113423, 1.58731077]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [203]:
# your code/answer here
print(a)
print('')
print(d)
#all values of d is +1 to a. 

[[[0.18735616 0.91996607 0.66168682 0.35465348 0.95358968]
  [0.1451573  0.17339121 0.5091223  0.02587329 0.46096725]
  [0.87327477 0.05154621 0.87417141 0.30936865 0.58303425]]

 [[0.59384567 0.08075741 0.73852591 0.70636762 0.03926711]
  [0.81522137 0.61002174 0.51947912 0.54601431 0.21277006]
  [0.44711181 0.35430245 0.75567209 0.12113423 0.58731077]]]

[[[1.18735616 1.91996607 1.66168682 1.35465348 1.95358968]
  [1.1451573  1.17339121 1.5091223  1.02587329 1.46096725]
  [1.87327477 1.05154621 1.87417141 1.30936865 1.58303425]]

 [[1.59384567 1.08075741 1.73852591 1.70636762 1.03926711]
  [1.81522137 1.61002174 1.51947912 1.54601431 1.21277006]
  [1.44711181 1.35430245 1.75567209 1.12113423 1.58731077]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [204]:
# your code here
e = a*c
e

array([[[0.18735616, 0.91996607, 0.66168682, 0.35465348, 0.95358968],
        [0.1451573 , 0.17339121, 0.5091223 , 0.02587329, 0.46096725],
        [0.87327477, 0.05154621, 0.87417141, 0.30936865, 0.58303425]],

       [[0.59384567, 0.08075741, 0.73852591, 0.70636762, 0.03926711],
        [0.81522137, 0.61002174, 0.51947912, 0.54601431, 0.21277006],
        [0.44711181, 0.35430245, 0.75567209, 0.12113423, 0.58731077]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [205]:
# your code/answer here

#Yes e equals to a since all values in c equal 1 the values of a don't change.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [206]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

1.953589683424962 1.0258732871058793 1.4736986838591146


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [207]:
# your code here
f = np.zeros(shape= (2,3,5), dtype=int)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [208]:
print(c)
print(d_min)
print(d_max)
d_mean


[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
1.0258732871058793
1.953589683424962


1.4736986838591146

In [209]:
for i in np.nditer(d):
    print (i)

1.1873561635563417
1.919966074327076
1.661686816952856
1.3546534810886135
1.953589683424962
1.1451572969305404
1.1733912051300015
1.509122297801041
1.0258732871058793
1.4609672458176601
1.873274768766524
1.0515462100790196
1.874171412500949
1.309368647268423
1.5830342486335418
1.59384567036281
1.0807574100466582
1.7385259056813651
1.7063676228894882
1.0392671131039057
1.81522137425386
1.6100217409523223
1.5194791151093128
1.5460143103597543
1.2127700625232043
1.4471118087733195
1.3543024531847898
1.7556720874288474
1.1211342273769582
1.5873107743434052


In [238]:
# your code here
d = a+c
f =[]
for i in np.nditer(d):
    
            if i>d_min and i<d_mean:
                f+=[25]
            elif i>d_mean and i<d_max:
                f+=[75]
            elif i==d_mean:
                f+=[50]
            elif i==d_min:
                f+=[0]
            elif i==d_max:
                f+=[100]

f = np.reshape(f, d.shape) 
print(d)
f



[[[1.18735616 1.91996607 1.66168682 1.35465348 1.95358968]
  [1.1451573  1.17339121 1.5091223  1.02587329 1.46096725]
  [1.87327477 1.05154621 1.87417141 1.30936865 1.58303425]]

 [[1.59384567 1.08075741 1.73852591 1.70636762 1.03926711]
  [1.81522137 1.61002174 1.51947912 1.54601431 1.21277006]
  [1.44711181 1.35430245 1.75567209 1.12113423 1.58731077]]]


array([[[ 25,  75,  75,  25, 100],
        [ 25,  25,  75,   0,  25],
        [ 75,  25,  75,  25,  75]],

       [[ 75,  25,  75,  75,  25],
        [ 75,  75,  75,  75,  25],
        [ 25,  25,  75,  25,  75]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [239]:
# your code here
print(d)
print('')
print(f)

[[[1.18735616 1.91996607 1.66168682 1.35465348 1.95358968]
  [1.1451573  1.17339121 1.5091223  1.02587329 1.46096725]
  [1.87327477 1.05154621 1.87417141 1.30936865 1.58303425]]

 [[1.59384567 1.08075741 1.73852591 1.70636762 1.03926711]
  [1.81522137 1.61002174 1.51947912 1.54601431 1.21277006]
  [1.44711181 1.35430245 1.75567209 1.12113423 1.58731077]]]

[[[ 25  75  75  25 100]
  [ 25  25  75   0  25]
  [ 75  25  75  25  75]]

 [[ 75  25  75  75  25]
  [ 75  75  75  75  25]
  [ 25  25  75  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [240]:
# your code here
for i in np.nditer(f):
    if i == 0:
        f=['E']
    elif i == 25:
        f=['D']
    elif i == 50:
        f=['C']
    elif i== 75:
        f=['B']
    elif i == 100:
        f=['A']
f
    


['B']